AWSTemplateFormatVersion: '2010-09-09'
Description: 'Hello World Lambda function that reads from S3 bucket'

Parameters:
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket to read from (required)
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '^[a-z0-9][a-z0-9.-]*[a-z0-9]$'
    ConstraintDescription: Must be a valid S3 bucket name (3-63 chars, lowercase letters, numbers, dots, and hyphens)

Resources:
  # IAM Role for Lambda function
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3ReadPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${S3BucketName}'
                  - !Sub 'arn:aws:s3:::${S3BucketName}/*'

  # Lambda function
  HelloWorldS3Function:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HelloWorldS3Reader
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          import os
          import boto3
          from botocore.exceptions import ClientError

          def lambda_handler(event, context):
              print("Hello World! Starting S3 bucket read operation...")
              bucket_name = event.get('bucket_name') or os.environ.get('S3_BUCKET_NAME')
              if not bucket_name:
                  return {
                      'statusCode': 400,
                      'body': json.dumps({
                          'message': 'Error: No bucket name provided. Please specify bucket_name in event or S3_BUCKET_NAME environment variable.',
                          'hello': 'world'
                      })
                  }
              s3_client = boto3.client('s3')
              try:
                  response = s3_client.list_objects_v2(Bucket=bucket_name, MaxKeys=10)
                  objects = []
                  if 'Contents' in response:
                      for obj in response['Contents']:
                          objects.append({
                              'key': obj['Key'],
                              'size': obj['Size'],
                              'last_modified': obj['LastModified'].isoformat()
                          })
                  message = f"Hello World! Successfully read from S3 bucket: {bucket_name}"
                  return {
                      'statusCode': 200,
                      'body': json.dumps({
                          'message': message,
                          'bucket': bucket_name,
                          'object_count': len(objects),
                          'objects': objects,
                          'hello': 'world'
                      })
                  }
              except ClientError as e:
                  return {
                      'statusCode': 500,
                      'body': json.dumps({
                          'message': f'Error reading from S3 bucket',
                          'error': str(e),
                          'hello': 'world'
                      })
                  }
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
      Timeout: 30
      MemorySize: 128

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt HelloWorldS3Function.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunctionArn'

  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref HelloWorldS3Function
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunctionName'

  LambdaExecutionRoleArn:
    Description: ARN of the Lambda execution role
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaExecutionRoleArn'
