AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to deploy Lambda function code from GitHub'

Parameters:
  FunctionName:
    Type: String
    Description: Name of the Lambda function to update
    Default: HelloWorldLambda

  S3Bucket:
    Type: String
    Description: S3 bucket containing the Lambda deployment package

  S3Key:
    Type: String
    Description: S3 key for the Lambda deployment package
    Default: lambda-deployment.zip

  Runtime:
    Type: String
    Description: Python runtime version
    Default: python3.11
    AllowedValues:
      - python3.9
      - python3.10
      - python3.11
      - python3.12

  Handler:
    Type: String
    Description: Lambda function handler
    Default: lambda_function.lambda_handler

  MemorySize:
    Type: Number
    Description: Memory size in MB
    Default: 128
    MinValue: 128
    MaxValue: 10240

  Timeout:
    Type: Number
    Description: Timeout in seconds
    Default: 30
    MinValue: 1
    MaxValue: 900

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${FunctionName}-DeploymentRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub 'arn:aws:s3:::${S3Bucket}/${S3Key}'
      Tags:
        - Key: Name
          Value: !Sub '${FunctionName}-DeploymentRole'

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Runtime: !Ref Runtime
      Handler: !Ref Handler
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: !Ref MemorySize
      Timeout: !Ref Timeout
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
      Tags:
        - Key: Name
          Value: !Ref FunctionName
        - Key: DeploymentMethod
          Value: GitHub-S3

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${FunctionName}'
      RetentionInDays: 7

  # Lambda version for deployment tracking
  LambdaVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref LambdaFunction
      Description: !Sub 'Version deployed at ${AWS::StackName}'

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaArn'

  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref LambdaFunction
    Export:
      Name: !Sub '${AWS::StackName}-LambdaName'

  LambdaVersionArn:
    Description: ARN of the Lambda version
    Value: !Ref LambdaVersion
    Export:
      Name: !Sub '${AWS::StackName}-VersionArn'

  LambdaExecutionRoleArn:
    Description: ARN of the Lambda execution role
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'
